
image: node:10.15.0

stages:
  - build
  - production
  
proses compile:
  stage: build
  script: 
    - npm install

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=sampanhorev1 --api-key=c85d2a15-e3b7-4ff6-a1cc-908b539eee94
  
  only:
    - master
